# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Description of what the lane does"
  lane :to_pgyer do
    # add actions here: https://docs.fastlane.tools/actions
    	time = Time.new.strftime("%Y%m%d") #获取时间格式
    version = get_version_number#获取版本号
    ipaName = "Release_#{version}_#{time}.ipa"# 输出后的ipa的名字
    
  	gym(
       clean:false,# 清除上次的构建
       scheme:"LWCollectionView", #项目名称
       export_method:"ad-hoc",#打包的类型(app-store,ad-hoc,enterprise,development）
       configuration:"Release",#模式，默认Release，还有Debug
       output_name:"#{ipaName}",#输出的包名
       output_directory:"./build",#输出的位置
       export_xcargs:"-allowProvisioningUpdates",#访问钥匙串
     )

    api_key = "419b50153dad7fa0365333e06f8a490c"
    user_key = "01f02af4d5e46d64fc5bd40ba5c2bb1a"
    pgyer(api_key:"#{api_key}",user_key:"#{user_key}")
  end
end
